// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDms_qYFUQ-xo7gJ6V_Uhxx1pLo-sdq_oQ',
    appId: '1:102295737240:web:0ca9bf36b116886a2c91ed',
    messagingSenderId: '102295737240',
    projectId: 'lordschool-25d63',
    authDomain: 'lordschool-25d63.firebaseapp.com',
    storageBucket: 'lordschool-25d63.appspot.com',
    measurementId: 'G-CD8CJ8206V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDae5AjLa4EAP1YcddPhx-EfgG4pOvG7dg',
    appId: '1:102295737240:android:50ddf95a4012c14c2c91ed',
    messagingSenderId: '102295737240',
    projectId: 'lordschool-25d63',
    storageBucket: 'lordschool-25d63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBenaM-quiNMFZPazsDiABPYvDGefJHorQ',
    appId: '1:102295737240:ios:04a342feef9f09702c91ed',
    messagingSenderId: '102295737240',
    projectId: 'lordschool-25d63',
    storageBucket: 'lordschool-25d63.appspot.com',
    iosClientId: '102295737240-i4q2j80p115jakvktmufrnr1m6er9fkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.lordSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBenaM-quiNMFZPazsDiABPYvDGefJHorQ',
    appId: '1:102295737240:ios:04a342feef9f09702c91ed',
    messagingSenderId: '102295737240',
    projectId: 'lordschool-25d63',
    storageBucket: 'lordschool-25d63.appspot.com',
    iosClientId: '102295737240-i4q2j80p115jakvktmufrnr1m6er9fkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.lordSchool',
  );
}
